# Generated by Django 5.2.12 on 2026-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(blank=True, null=True),
        ),
    ]
