# Generated by Django 5.2.12 on 2026-04-04 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_people_birth_year_alter_people_eye_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name'),
        ),
    ]
